version: "3"

services:

  mongodb:
    container_name: database_container
    image: mongo:latest
    ports:
      - "2717:27017"
    volumes:
      - mongodb:/data/db

  app:
    build: .
    ports:
      - "3000:8000"
    environment:
      - PORT=8000
      - DB_URI=mongodb://mongodb:27017

volumes:
  mongodb: